# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestructuredtextMarkupItem',
        ),
        migrations.DeleteModel(
            name='TextileMarkupItem',
        ),
    ]
